name: '1:11 Mandate'
favicon: null
layout_spectrum: 0.28055
typography_spectrum: 0.48087
title: To Live Is Christ
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dddee0'
    - '#1b262c'
    - '#aab1b7'
    - '#384f57'
    - '#849199'
  brandStrength: 1
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
